require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContainsController do

  # This should return the minimal set of attributes required to create a valid
  # Contain. As you add validations to Contain, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContainsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all contains as @contains" do
      contain = Contain.create! valid_attributes
      get :index, {}, valid_session
      assigns(:contains).should eq([contain])
    end
  end

  describe "GET show" do
    it "assigns the requested contain as @contain" do
      contain = Contain.create! valid_attributes
      get :show, {:id => contain.to_param}, valid_session
      assigns(:contain).should eq(contain)
    end
  end

  describe "GET new" do
    it "assigns a new contain as @contain" do
      get :new, {}, valid_session
      assigns(:contain).should be_a_new(Contain)
    end
  end

  describe "GET edit" do
    it "assigns the requested contain as @contain" do
      contain = Contain.create! valid_attributes
      get :edit, {:id => contain.to_param}, valid_session
      assigns(:contain).should eq(contain)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Contain" do
        expect {
          post :create, {:contain => valid_attributes}, valid_session
        }.to change(Contain, :count).by(1)
      end

      it "assigns a newly created contain as @contain" do
        post :create, {:contain => valid_attributes}, valid_session
        assigns(:contain).should be_a(Contain)
        assigns(:contain).should be_persisted
      end

      it "redirects to the created contain" do
        post :create, {:contain => valid_attributes}, valid_session
        response.should redirect_to(Contain.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contain as @contain" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contain.any_instance.stub(:save).and_return(false)
        post :create, {:contain => {}}, valid_session
        assigns(:contain).should be_a_new(Contain)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contain.any_instance.stub(:save).and_return(false)
        post :create, {:contain => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contain" do
        contain = Contain.create! valid_attributes
        # Assuming there are no other contains in the database, this
        # specifies that the Contain created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Contain.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => contain.to_param, :contain => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested contain as @contain" do
        contain = Contain.create! valid_attributes
        put :update, {:id => contain.to_param, :contain => valid_attributes}, valid_session
        assigns(:contain).should eq(contain)
      end

      it "redirects to the contain" do
        contain = Contain.create! valid_attributes
        put :update, {:id => contain.to_param, :contain => valid_attributes}, valid_session
        response.should redirect_to(contain)
      end
    end

    describe "with invalid params" do
      it "assigns the contain as @contain" do
        contain = Contain.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contain.any_instance.stub(:save).and_return(false)
        put :update, {:id => contain.to_param, :contain => {}}, valid_session
        assigns(:contain).should eq(contain)
      end

      it "re-renders the 'edit' template" do
        contain = Contain.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contain.any_instance.stub(:save).and_return(false)
        put :update, {:id => contain.to_param, :contain => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contain" do
      contain = Contain.create! valid_attributes
      expect {
        delete :destroy, {:id => contain.to_param}, valid_session
      }.to change(Contain, :count).by(-1)
    end

    it "redirects to the contains list" do
      contain = Contain.create! valid_attributes
      delete :destroy, {:id => contain.to_param}, valid_session
      response.should redirect_to(contains_url)
    end
  end

end
