require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SubmittedAnswersController do

  # This should return the minimal set of attributes required to create a valid
  # SubmittedAnswer. As you add validations to SubmittedAnswer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SubmittedAnswersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all submitted_answers as @submitted_answers" do
      submitted_answer = SubmittedAnswer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:submitted_answers).should eq([submitted_answer])
    end
  end

  describe "GET show" do
    it "assigns the requested submitted_answer as @submitted_answer" do
      submitted_answer = SubmittedAnswer.create! valid_attributes
      get :show, {:id => submitted_answer.to_param}, valid_session
      assigns(:submitted_answer).should eq(submitted_answer)
    end
  end

  describe "GET new" do
    it "assigns a new submitted_answer as @submitted_answer" do
      get :new, {}, valid_session
      assigns(:submitted_answer).should be_a_new(SubmittedAnswer)
    end
  end

  describe "GET edit" do
    it "assigns the requested submitted_answer as @submitted_answer" do
      submitted_answer = SubmittedAnswer.create! valid_attributes
      get :edit, {:id => submitted_answer.to_param}, valid_session
      assigns(:submitted_answer).should eq(submitted_answer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SubmittedAnswer" do
        expect {
          post :create, {:submitted_answer => valid_attributes}, valid_session
        }.to change(SubmittedAnswer, :count).by(1)
      end

      it "assigns a newly created submitted_answer as @submitted_answer" do
        post :create, {:submitted_answer => valid_attributes}, valid_session
        assigns(:submitted_answer).should be_a(SubmittedAnswer)
        assigns(:submitted_answer).should be_persisted
      end

      it "redirects to the created submitted_answer" do
        post :create, {:submitted_answer => valid_attributes}, valid_session
        response.should redirect_to(SubmittedAnswer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved submitted_answer as @submitted_answer" do
        # Trigger the behavior that occurs when invalid params are submitted
        SubmittedAnswer.any_instance.stub(:save).and_return(false)
        post :create, {:submitted_answer => {}}, valid_session
        assigns(:submitted_answer).should be_a_new(SubmittedAnswer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SubmittedAnswer.any_instance.stub(:save).and_return(false)
        post :create, {:submitted_answer => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested submitted_answer" do
        submitted_answer = SubmittedAnswer.create! valid_attributes
        # Assuming there are no other submitted_answers in the database, this
        # specifies that the SubmittedAnswer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SubmittedAnswer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => submitted_answer.to_param, :submitted_answer => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested submitted_answer as @submitted_answer" do
        submitted_answer = SubmittedAnswer.create! valid_attributes
        put :update, {:id => submitted_answer.to_param, :submitted_answer => valid_attributes}, valid_session
        assigns(:submitted_answer).should eq(submitted_answer)
      end

      it "redirects to the submitted_answer" do
        submitted_answer = SubmittedAnswer.create! valid_attributes
        put :update, {:id => submitted_answer.to_param, :submitted_answer => valid_attributes}, valid_session
        response.should redirect_to(submitted_answer)
      end
    end

    describe "with invalid params" do
      it "assigns the submitted_answer as @submitted_answer" do
        submitted_answer = SubmittedAnswer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SubmittedAnswer.any_instance.stub(:save).and_return(false)
        put :update, {:id => submitted_answer.to_param, :submitted_answer => {}}, valid_session
        assigns(:submitted_answer).should eq(submitted_answer)
      end

      it "re-renders the 'edit' template" do
        submitted_answer = SubmittedAnswer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SubmittedAnswer.any_instance.stub(:save).and_return(false)
        put :update, {:id => submitted_answer.to_param, :submitted_answer => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested submitted_answer" do
      submitted_answer = SubmittedAnswer.create! valid_attributes
      expect {
        delete :destroy, {:id => submitted_answer.to_param}, valid_session
      }.to change(SubmittedAnswer, :count).by(-1)
    end

    it "redirects to the submitted_answers list" do
      submitted_answer = SubmittedAnswer.create! valid_attributes
      delete :destroy, {:id => submitted_answer.to_param}, valid_session
      response.should redirect_to(submitted_answers_url)
    end
  end

end
